import type { Country } from './types.js';

/** This public pool does not identify which country the server selected. */
export const COUNTRIES: readonly Country[] = [
  { id: 'AR', name: 'Argentina' },
  { id: 'AU', name: 'Australia' },
  { id: 'AT', name: 'Austria' },
  { id: 'BR', name: 'Brazil' },
  { id: 'CA', name: 'Canada' },
  { id: 'CL', name: 'Chile' },
  { id: 'CN', name: 'China' },
  { id: 'CO', name: 'Colombia' },
  { id: 'HR', name: 'Croatia' },
  { id: 'EG', name: 'Egypt' },
  { id: 'FR', name: 'France' },
  { id: 'DE', name: 'Germany' },
  { id: 'GH', name: 'Ghana' },
  { id: 'GR', name: 'Greece' },
  { id: 'IS', name: 'Iceland' },
  { id: 'IN', name: 'India' },
  { id: 'ID', name: 'Indonesia' },
  { id: 'IE', name: 'Ireland' },
  { id: 'IT', name: 'Italy' },
  { id: 'JP', name: 'Japan' },
  { id: 'KE', name: 'Kenya' },
  { id: 'MY', name: 'Malaysia' },
  { id: 'MX', name: 'Mexico' },
  { id: 'MA', name: 'Morocco' },
  { id: 'NP', name: 'Nepal' },
  { id: 'NL', name: 'Netherlands' },
  { id: 'NZ', name: 'New Zealand' },
  { id: 'NG', name: 'Nigeria' },
  { id: 'NO', name: 'Norway' },
  { id: 'PK', name: 'Pakistan' },
  { id: 'PE', name: 'Peru' },
  { id: 'PH', name: 'Philippines' },
  { id: 'PT', name: 'Portugal' },
  { id: 'SA', name: 'Saudi Arabia' },
  { id: 'SG', name: 'Singapore' },
  { id: 'ZA', name: 'South Africa' },
  { id: 'KR', name: 'South Korea' },
  { id: 'ES', name: 'Spain' },
  { id: 'SE', name: 'Sweden' },
  { id: 'TH', name: 'Thailand' },
  { id: 'TR', name: 'Turkey' },
  { id: 'AE', name: 'United Arab Emirates' },
  { id: 'GB', name: 'United Kingdom' },
  { id: 'US', name: 'United States' },
  { id: 'VN', name: 'Vietnam' },
];
